import type { Delivery } from "@/lib/types";

// A fully-defaulted Delivery with the given overrides — used to build orders
// entirely client-side (teaching-mode sandbox, where nothing is written to the
// DB, so the row never comes back from an insert).
export function blankDelivery(over: Partial<Delivery> = {}): Delivery {
  const now = new Date().toISOString();
  return {
    id: "",
    order_no: 0,
    order_code: null,
    order_suffix: null,
    stage: "draft",
    rejected_reason: null,
    canceled_reason: null, canceled_reason_note: null, canceled_by: null, canceled_at: null,
    is_training: true,
    redelivery_of: null,
    redelivery_reason: null,
    order_type: null,
    store: null,
    po2: null,
    so_num: null,
    invoice_num: null,
    estimate_num: null,
    input_date: null,
    input_time: null,
    delivery_date: null,
    pickup_name: null,
    pickup_address: null,
    pickup_duration: null,
    delivery_fee: null,
    est_pallets: null,
    actual_pallets: null,
    assigned_driver: null,
    route_seq: null,
    load_no: null,
    load_auto: false,
    delivery_duration: null,
    delivery_name: null,
    delivery_address: null,
    delivery_windows: null,
    account: null,
    contact: null,
    delivery_phone: null,
    delivery_notes: null,
    route_miles: null,
    route_duration: null,
    route_provider: null,
    route_traffic: null,
    pod_received_by: null,
    pod_signature: null,
    pod_delivered_at: null,
    departed_at: null,
    arrived_at: null,
    photos: null,
    pickup_lat: null,
    pickup_lng: null,
    pickup_gps_at: null,
    pod_lat: null,
    pod_lng: null,
    pod_accuracy: null,
    delivery_lat: null,
    delivery_lng: null,
    delivery_pin_source: null,
    created_by: null,
    assigned_sales_rep: null,
    approved_by: null,
    approved_at: null,
    csat_rating: null,
    csat_comment: null,
    created_at: now,
    updated_at: now,
    ...over,
  };
}
