-- ============================================================
-- Deliveries App — Supabase schema
-- Run this in Supabase Dashboard → SQL Editor (one time).
-- Then run roles.sql to enable user roles & management.
--
-- Model: single shared team workspace. Any authenticated user can
-- READ every row. WRITE is gated by role via RLS + the stage guard
-- (see roles.sql). Auth is handled by Supabase Auth.
-- ============================================================

-- ---------- Extensions ----------
create extension if not exists "pgcrypto";

-- ---------- Profiles (one row per auth user) ----------
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  full_name   text,
  avatar_url  text,
  created_at  timestamptz not null default now()
);

-- Auto-create a profile row when a new user signs up. full_name + role
-- travel in user metadata (set on invite/signup) and are applied here.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'sales')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- Settings (singleton row, id = 1) ----------
-- The editable pick-lists that drive the order form dropdowns.
create table if not exists public.settings (
  id           int primary key default 1,
  app_name     text not null default 'RDZ·DELIVERIES',
  -- stores & drivers are lists of {name, address} so the address is map-searchable.
  stores       jsonb not null default '[{"name":"Brownsville","address":""},{"name":"Weslaco","address":""},{"name":"Pharr","address":""},{"name":"McAllen","address":""},{"name":"Mission","address":""},{"name":"Edinburg","address":""}]'::jsonb,
  order_types  text[] not null default array['Customer','Intertienda','Transfer'],
  -- Per-type field rules keyed by type name: {storeToStore: bool, docRef: 'invoice'|'any'|'none'}.
  order_type_rules jsonb not null default '{"Customer":{"storeToStore":false,"docRef":"invoice"},"Intertienda":{"storeToStore":true,"docRef":"any","homeIsDestination":true},"Transfer":{"storeToStore":true,"docRef":"estimate"}}'::jsonb,
  drivers      jsonb not null default '[]'::jsonb,
  -- Minutes added per pallet, used to auto-calculate durations. Admin-editable.
  pickup_min_per_pallet   numeric not null default 4,
  delivery_min_per_pallet numeric not null default 5,
  help_email   text,   -- Help-button recipient (falls back to DEFAULT_HELP_EMAIL)
  help_phone   text,   -- Optional support phone → "Call" link on the Help button
  updated_at   timestamptz not null default now(),
  constraint settings_singleton check (id = 1)
);
insert into public.settings (id) values (1) on conflict (id) do nothing;

-- ---------- Deliveries (the orders) ----------
-- `order_no` is the human-facing sequential ID shown in the UI.
-- `stage` is the approval/fulfillment workflow state:
--   draft → pending → approved → fulfilling → ready → delivered
--   (with `rejected` and `canceled` as off-ramps)
create table if not exists public.deliveries (
  id                 uuid primary key default gen_random_uuid(),
  order_no           bigint generated by default as identity,

  -- Workflow
  stage              text not null default 'draft',
  rejected_reason    text,

  -- Re-delivery tracking (repeats logged as new linked orders)
  redelivery_of      uuid references public.deliveries(id) on delete set null,
  redelivery_reason  text,

  -- Data columns (from the spec)
  order_type         text,                     -- Order Type
  store              text,                     -- Store (Sold From)
  order_code         text,                     -- human-facing id, e.g. "FA100" (see lib/order-code)
  po2                text,                     -- PO #
  so_num             text,                     -- SO #
  invoice_num        text,                     -- Invoice #
  estimate_num       text,                     -- Estimate # (Transfer)
  input_date         date default current_date,-- Input Date
  input_time         text,                     -- Input Military Time (e.g. 1430)
  delivery_date      date,                     -- Delivery Date
  pickup_name        text,                     -- Pickup Name
  pickup_address     text,                     -- Pickup Address
  pickup_duration    text,                     -- Pickup Duration
  est_pallets        numeric,                  -- Est. Pallets (estimated by sales)
  actual_pallets     numeric,                  -- Actual Pallets (revised by warehouse)
  assigned_driver    text,                     -- Assigned Driver (optional)
  delivery_duration  text,                     -- Delivery Duration
  delivery_address   text,                     -- Delivery Address
  delivery_windows   text,                     -- Delivery Military Time Windows
  account            text,                     -- Account
  contact            text,                     -- Contact
  delivery_phone     text,                     -- Delivery Phone Number
  delivery_notes     text,                     -- Delivery Notes

  -- Auto-computed route (pickup → delivery) from the routing web service
  route_miles        numeric,
  route_duration     text,
  route_provider     text,
  route_traffic      boolean,

  -- Audit
  created_by         uuid references public.profiles(id) on delete set null,
  approved_by        uuid references public.profiles(id) on delete set null,
  approved_at        timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists deliveries_stage_idx on public.deliveries(stage);
create index if not exists deliveries_delivery_date_idx on public.deliveries(delivery_date);
create index if not exists deliveries_created_by_idx on public.deliveries(created_by);

-- ---------- Order activity log (audit trail) ----------
create table if not exists public.order_events (
  id           uuid primary key default gen_random_uuid(),
  delivery_id  uuid not null references public.deliveries(id) on delete cascade,
  kind         text not null,           -- created / submitted / approved / rejected / fulfilling / ready / delivered / edited / canceled
  note         text,
  created_by   uuid references public.profiles(id) on delete set null,
  created_at   timestamptz not null default now()
);
create index if not exists order_events_delivery_idx on public.order_events(delivery_id);

-- ---------- Notifications (role-targeted, in-app) ----------
-- One row per recipient. Created when an order changes stage:
--   → pending    all managers      "an order needs approval"
--   → approved   all warehouse     "ready to fulfill"  + the creator "your order was approved"
--   → rejected   the creator       "your order was rejected (reason)"
create table if not exists public.notifications (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles(id) on delete cascade,  -- recipient
  delivery_id  uuid references public.deliveries(id) on delete cascade,
  order_no     bigint,
  kind         text not null,           -- pending / approved / rejected / ready / delivered
  message      text not null,
  read         boolean not null default false,
  created_at   timestamptz not null default now()
);
create index if not exists notifications_user_idx on public.notifications(user_id, read);

-- ---------- updated_at trigger for deliveries ----------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists deliveries_touch on public.deliveries;
create trigger deliveries_touch before update on public.deliveries
  for each row execute function public.touch_updated_at();

-- ============================================================
-- Row Level Security. Baseline: any authenticated user can READ.
-- WRITE baseline is open here; roles.sql tightens deliveries writes
-- to the correct role per workflow stage.
-- ============================================================
alter table public.profiles     enable row level security;
alter table public.settings     enable row level security;
alter table public.deliveries   enable row level security;
alter table public.order_events enable row level security;

-- ⚠ ESTE BUCLE ES UNA LINEA BASE, Y VOLVER A CORRERLO CONTRA UNA BASE VIVA LA ABRE ENTERA.
-- El `drop policy` + `create ... using (true)` de abajo deshace, de golpe y en silencio, todo lo que
-- las migraciones numeradas fueron estrechando encima: la rama por rol de la 011/015, el acceso por
-- modulo de la 083 y, desde la 131, el filtro por tienda. Y la de escritura nace `for all`, que
-- INCLUYE SELECT: las politicas permisivas se suman con OR, asi que con ella puesta la de lectura no
-- decide nada (D-100, confirmado ensayando la 131 contra produccion).
--
-- Se deja como esta A PROPOSITO, y no es descuido:
--   * `083_deliveries_access.sql:69` hace `alter policy "auth write deliveries"` a secas. Si el bucle
--     dejara de crearla, una reconstruccion desde cero fallaria ahi, y una migracion ya aplicada no
--     se edita.
--   * Partir solo esa politica en tres arreglaria una de las dos vias y dejaria la otra: la de
--     LECTURA volveria igual a `using (true)`. Un arreglo a medias aqui invita a creer que el fichero
--     se puede volver a correr, y no se puede.
-- La proteccion de verdad es la autocomprobacion de la 131, que se niega a dejar NINGUNA otra
-- politica permisiva otorgando SELECT sobre `deliveries`. Si alguna vez se reconstruye el esquema,
-- hay que volver a aplicar las migraciones numeradas, en orden.
do $$
declare t text;
begin
  foreach t in array array['profiles','settings','deliveries','order_events']
  loop
    execute format('drop policy if exists "auth read %1$s" on public.%1$s', t);
    execute format('drop policy if exists "auth write %1$s" on public.%1$s', t);
    execute format($f$create policy "auth read %1$s" on public.%1$s for select to authenticated using (true)$f$, t);
    execute format($f$create policy "auth write %1$s" on public.%1$s for all to authenticated using (true) with check (true)$f$, t);
  end loop;
end $$;

-- ---------- Notifications RLS ----------
-- A recipient only ever sees (and dismisses) their own notifications. Any
-- authenticated user may create them, since the actor fans a stage change
-- out to other people's inboxes.
alter table public.notifications enable row level security;
drop policy if exists "notif read own"   on public.notifications;
drop policy if exists "notif insert any" on public.notifications;
drop policy if exists "notif update own" on public.notifications;
create policy "notif read own"   on public.notifications for select to authenticated using (user_id = auth.uid());
create policy "notif insert any" on public.notifications for insert to authenticated with check (true);
create policy "notif update own" on public.notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------- Realtime ----------
alter publication supabase_realtime add table public.deliveries;
alter publication supabase_realtime add table public.order_events;
alter publication supabase_realtime add table public.settings;
alter publication supabase_realtime add table public.notifications;
